package cmd

const (
	BFP_FIB_LOOKUP_DIRECT = uint32(1) << 0
	BFP_FIB_LOOKUP_OUTPUT = uint32(1) << 1
)

const (
	BPF_FIB_LKUP_RET_SUCCESS = iota
	BPF_FIB_LKUP_RET_BLACKHOLE
	BPF_FIB_LKUP_RET_UNREACHABLE
	BPF_FIB_LKUP_RET_PROHIBIT
	BPF_FIB_LKUP_RET_NOT_FWDED
	BPF_FIB_LKUP_RET_FWD_DISABLED
	BPF_FIB_LKUP_RET_UNSUPP_LWT
	BPF_FIB_LKUP_RET_NO_NEIGH
	BPF_FIB_LKUP_RET_FRAG_NEEDED
)
